// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ftoken.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'exchange.freezed.dart';

class ExchangeAsset {
  final FTokenInfo token;
  final Set<ExchangeProvider> providers;
  final bool halted;

  const ExchangeAsset({
    required this.token,
    required this.providers,
    required this.halted,
  });

  @override
  int get hashCode => token.hashCode ^ providers.hashCode ^ halted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExchangeAsset &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          providers == other.providers &&
          halted == other.halted;
}

@freezed
sealed class ExchangeProvider with _$ExchangeProvider {
  const ExchangeProvider._();

  const factory ExchangeProvider.thorchain(
    BigInt field0,
  ) = ExchangeProvider_Thorchain;
  const factory ExchangeProvider.uniswap(
    UniswapMeta field0,
  ) = ExchangeProvider_Uniswap;
  const factory ExchangeProvider.zIlSwap(
    BigInt field0,
  ) = ExchangeProvider_ZIlSwap;
  const factory ExchangeProvider.sunSwap(
    BigInt field0,
  ) = ExchangeProvider_SunSwap;
}

class ExchangeQuoteInfo {
  final ExchangeProvider provider;
  final String amountOut;
  final int? feeTier;
  final String? permitTypedDataJson;
  final BigInt? permitNonce;

  const ExchangeQuoteInfo({
    required this.provider,
    required this.amountOut,
    this.feeTier,
    this.permitTypedDataJson,
    this.permitNonce,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      amountOut.hashCode ^
      feeTier.hashCode ^
      permitTypedDataJson.hashCode ^
      permitNonce.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExchangeQuoteInfo &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          amountOut == other.amountOut &&
          feeTier == other.feeTier &&
          permitTypedDataJson == other.permitTypedDataJson &&
          permitNonce == other.permitNonce;
}

/// FFI-safe Uniswap deployment metadata. Addresses are hex `0x...` strings so the
/// whole struct crosses the flutter_rust_bridge boundary; they are parsed into alloy
/// `Address` once, internally, via [`UniswapMeta::resolve`].
class UniswapMeta {
  final BigInt chainId;
  final String universalRouter;
  final String quoterV2;
  final String permit2;
  final String weth;

  const UniswapMeta({
    required this.chainId,
    required this.universalRouter,
    required this.quoterV2,
    required this.permit2,
    required this.weth,
  });

  @override
  int get hashCode =>
      chainId.hashCode ^
      universalRouter.hashCode ^
      quoterV2.hashCode ^
      permit2.hashCode ^
      weth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UniswapMeta &&
          runtimeType == other.runtimeType &&
          chainId == other.chainId &&
          universalRouter == other.universalRouter &&
          quoterV2 == other.quoterV2 &&
          permit2 == other.permit2 &&
          weth == other.weth;
}
