// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../models/exchange.dart';
import '../../models/exchange/pancakeswap.dart';
import '../../models/exchange/plunderswap.dart';
import '../../models/exchange/relay.dart';
import '../../models/exchange/uniswap.dart';
import '../../models/ftoken.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `chain_matches_network`

Future<List<ExchangeAsset>> bootstrapExchangeProviders(
        {required BigInt walletIndex, required BigInt accountIndex}) =>
    RustLib.instance.api.crateApiExchangeBootstrapBootstrapExchangeProviders(
        walletIndex: walletIndex, accountIndex: accountIndex);

Future<ExchangeAsset> refreshExchangeQuotes(
        {required ExchangeAsset from,
        required ExchangeAsset to,
        required String amount}) =>
    RustLib.instance.api.crateApiExchangeBootstrapRefreshExchangeQuotes(
        from: from, to: to, amount: amount);
