// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../models/exchange.dart';
import '../../models/exchange/pancakeswap.dart';
import '../../models/exchange/relay.dart';
import '../../models/exchange/uniswap.dart';
import '../../models/ftoken.dart';
import '../../models/transactions/access_list.dart';
import '../../models/transactions/base_token.dart';
import '../../models/transactions/btc.dart';
import '../../models/transactions/evm.dart';
import '../../models/transactions/request.dart';
import '../../models/transactions/scilla.dart';
import '../../models/transactions/transaction_metadata.dart';
import '../../models/transactions/tron.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_relay_tron_origin`

Future<TransactionRequestInfo?> checkExchangeApproval(
        {required SwapAuth auth,
        required SwapParams params,
        required BigInt nonce,
        required String approveTitle}) =>
    RustLib.instance.api.crateApiExchangeLedgerCheckExchangeApproval(
        auth: auth, params: params, nonce: nonce, approveTitle: approveTitle);

Future<PreparedSwapInfo> prepareExchangeSwap({required SwapParams params}) =>
    RustLib.instance.api
        .crateApiExchangeLedgerPrepareExchangeSwap(params: params);

Future<TransactionRequestInfo> finalizeExchangeSwap(
        {required SwapAuth auth,
        required ExchangeProvider provider,
        required String quoteBlob,
        String? permitSignature,
        required BigInt nonce,
        required ExchangeTxDisplay display}) =>
    RustLib.instance.api.crateApiExchangeLedgerFinalizeExchangeSwap(
        auth: auth,
        provider: provider,
        quoteBlob: quoteBlob,
        permitSignature: permitSignature,
        nonce: nonce,
        display: display);

Future<BigInt> estimateSwapBaseNonce(
        {required BigInt walletIndex, required BigInt accountIndex}) =>
    RustLib.instance.api.crateApiExchangeLedgerEstimateSwapBaseNonce(
        walletIndex: walletIndex, accountIndex: accountIndex);

class PreparedSwapInfo {
  final String? permitTypedDataJson;
  final String quoteBlob;

  const PreparedSwapInfo({
    this.permitTypedDataJson,
    required this.quoteBlob,
  });

  @override
  int get hashCode => permitTypedDataJson.hashCode ^ quoteBlob.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreparedSwapInfo &&
          runtimeType == other.runtimeType &&
          permitTypedDataJson == other.permitTypedDataJson &&
          quoteBlob == other.quoteBlob;
}
