// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../models/exchange/whitebird/orders.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Create a WhiteBird exchange session (`POST /api/sessions` on the proxy).
///
/// `from_amount` is a human decimal string. `destination_crypto_address` is the
/// payout address for buys; WhiteBird ignores it for sells but the proxy
/// requires the field, so pass the user's account address either way.
Future<WhiteBirdSessionInfo> whitebirdCreateSession(
        {required bool isTestnet,
        required String fromCode,
        required String toCode,
        required String fromAmount,
        required String destinationCryptoAddress,
        required String externalClientId}) =>
    RustLib.instance.api.crateApiExchangeWhitebirdWhitebirdCreateSession(
        isTestnet: isTestnet,
        fromCode: fromCode,
        toCode: toCode,
        fromAmount: fromAmount,
        destinationCryptoAddress: destinationCryptoAddress,
        externalClientId: externalClientId);

/// List open PROCESSING orders for the exchange-page badge/modal.
Future<List<WhiteBirdOpenOrder>> whitebirdOpenOrders(
        {required bool isTestnet,
        required String externalClientId,
        String? clientId}) =>
    RustLib.instance.api.crateApiExchangeWhitebirdWhitebirdOpenOrders(
        isTestnet: isTestnet,
        externalClientId: externalClientId,
        clientId: clientId);

/// Cancel an active order with the user's client JWT — the same call the
/// SDK's "cancel order" button makes.
Future<void> whitebirdRejectOrder(
        {required bool isTestnet,
        required String orderId,
        required String accessToken}) =>
    RustLib.instance.api.crateApiExchangeWhitebirdWhitebirdRejectOrder(
        isTestnet: isTestnet, orderId: orderId, accessToken: accessToken);
