// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BitcoinMetadataInfo {
  final List<TxOutInfo> witnessUtxos;
  final List<InputMetaInfo> inputMeta;

  const BitcoinMetadataInfo({
    required this.witnessUtxos,
    required this.inputMeta,
  });

  @override
  int get hashCode => witnessUtxos.hashCode ^ inputMeta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BitcoinMetadataInfo &&
          runtimeType == other.runtimeType &&
          witnessUtxos == other.witnessUtxos &&
          inputMeta == other.inputMeta;
}

class InputMetaInfo {
  final int addressType;
  final String derivationPath;

  const InputMetaInfo({
    required this.addressType,
    required this.derivationPath,
  });

  @override
  int get hashCode => addressType.hashCode ^ derivationPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputMetaInfo &&
          runtimeType == other.runtimeType &&
          addressType == other.addressType &&
          derivationPath == other.derivationPath;
}

class OutPointInfo {
  final String txid;
  final int vout;

  const OutPointInfo({
    required this.txid,
    required this.vout,
  });

  @override
  int get hashCode => txid.hashCode ^ vout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutPointInfo &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout;
}

class TransactionRequestBitcoin {
  final int version;
  final int lockTime;
  final List<TxInInfo> input;
  final List<TxOutInfo> output;

  const TransactionRequestBitcoin({
    required this.version,
    required this.lockTime,
    required this.input,
    required this.output,
  });

  @override
  int get hashCode =>
      version.hashCode ^ lockTime.hashCode ^ input.hashCode ^ output.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionRequestBitcoin &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          lockTime == other.lockTime &&
          input == other.input &&
          output == other.output;
}

class TxInInfo {
  final OutPointInfo previousOutput;
  final Uint8List scriptSig;
  final int sequence;
  final List<Uint8List> witness;

  const TxInInfo({
    required this.previousOutput,
    required this.scriptSig,
    required this.sequence,
    required this.witness,
  });

  @override
  int get hashCode =>
      previousOutput.hashCode ^
      scriptSig.hashCode ^
      sequence.hashCode ^
      witness.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxInInfo &&
          runtimeType == other.runtimeType &&
          previousOutput == other.previousOutput &&
          scriptSig == other.scriptSig &&
          sequence == other.sequence &&
          witness == other.witness;
}

class TxOutInfo {
  final BigInt value;
  final Uint8List scriptPubkey;

  const TxOutInfo({
    required this.value,
    required this.scriptPubkey,
  });

  @override
  int get hashCode => value.hashCode ^ scriptPubkey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxOutInfo &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          scriptPubkey == other.scriptPubkey;
}
