// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FRB/Dart-facing Solana history payload (typed, Bitcoin/Tron style).
class TransactionSolana {
  final Uint8List message;
  final Uint8List signature;

  /// Base58 signature string for UI / explorers.
  final String transactionHash;
  final BigInt? fee;
  final BigInt? slot;

  const TransactionSolana({
    required this.message,
    required this.signature,
    required this.transactionHash,
    this.fee,
    this.slot,
  });

  @override
  int get hashCode =>
      message.hashCode ^
      signature.hashCode ^
      transactionHash.hashCode ^
      fee.hashCode ^
      slot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionSolana &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          signature == other.signature &&
          transactionHash == other.transactionHash &&
          fee == other.fee &&
          slot == other.slot;
}
