// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FFI mirror of core `SolanaHistoryTransaction` (history path).
/// Byte fields are hex-encoded strings for FRB/Dart.
class TransactionSolana {
  final String message;
  final String signature;
  final BigInt? fee;
  final BigInt? slot;

  /// Base58 signature (Solana tx id).
  final String txId;

  const TransactionSolana({
    required this.message,
    required this.signature,
    this.fee,
    this.slot,
    required this.txId,
  });

  @override
  int get hashCode =>
      message.hashCode ^
      signature.hashCode ^
      fee.hashCode ^
      slot.hashCode ^
      txId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionSolana &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          signature == other.signature &&
          fee == other.fee &&
          slot == other.slot &&
          txId == other.txId;
}
