// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'tron.freezed.dart';

class TransactionRequestTron {
  final bool? visible;
  final String? txId;
  final TronRawDataInfo rawData;
  final String rawDataHex;

  /// Hex signature when present (signed history / WC-dApp response). Unsigned
  /// request payloads leave this as `None`.
  final String? signature;

  const TransactionRequestTron({
    this.visible,
    this.txId,
    required this.rawData,
    required this.rawDataHex,
    this.signature,
  });

  @override
  int get hashCode =>
      visible.hashCode ^
      txId.hashCode ^
      rawData.hashCode ^
      rawDataHex.hashCode ^
      signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionRequestTron &&
          runtimeType == other.runtimeType &&
          visible == other.visible &&
          txId == other.txId &&
          rawData == other.rawData &&
          rawDataHex == other.rawDataHex &&
          signature == other.signature;
}

class TronContractInfo {
  final String contractType;
  final String typeUrl;
  final TronContractValue value;

  const TronContractInfo({
    required this.contractType,
    required this.typeUrl,
    required this.value,
  });

  @override
  int get hashCode => contractType.hashCode ^ typeUrl.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TronContractInfo &&
          runtimeType == other.runtimeType &&
          contractType == other.contractType &&
          typeUrl == other.typeUrl &&
          value == other.value;
}

@freezed
sealed class TronContractValue with _$TronContractValue {
  const TronContractValue._();

  const factory TronContractValue.transferContract({
    required String ownerAddress,
    required String toAddress,
    required PlatformInt64 amount,
  }) = TronContractValue_TransferContract;
  const factory TronContractValue.triggerSmartContract({
    String? ownerAddress,
    String? contractAddress,
    PlatformInt64? callValue,
    String? data,
    PlatformInt64? callTokenValue,
    PlatformInt64? tokenId,
  }) = TronContractValue_TriggerSmartContract;
  const factory TronContractValue.freezeBalanceV2Contract({
    required String ownerAddress,
    required PlatformInt64 frozenBalance,
    required int resource,
  }) = TronContractValue_FreezeBalanceV2Contract;
  const factory TronContractValue.withdrawBalanceContract({
    required String ownerAddress,
  }) = TronContractValue_WithdrawBalanceContract;
  const factory TronContractValue.unfreezeBalanceV2Contract({
    required String ownerAddress,
    required PlatformInt64 unfreezeBalance,
    required int resource,
  }) = TronContractValue_UnfreezeBalanceV2Contract;
  const factory TronContractValue.withdrawExpireUnfreezeContract({
    required String ownerAddress,
  }) = TronContractValue_WithdrawExpireUnfreezeContract;
  const factory TronContractValue.delegateResourceContract({
    required String ownerAddress,
    required int resource,
    required PlatformInt64 balance,
    required String receiverAddress,
    required bool lock,
    required PlatformInt64 lockPeriod,
  }) = TronContractValue_DelegateResourceContract;
  const factory TronContractValue.unDelegateResourceContract({
    required String ownerAddress,
    required int resource,
    required PlatformInt64 balance,
    required String receiverAddress,
  }) = TronContractValue_UnDelegateResourceContract;
  const factory TronContractValue.cancelAllUnfreezeV2Contract({
    required String ownerAddress,
  }) = TronContractValue_CancelAllUnfreezeV2Contract;
  const factory TronContractValue.transferAssetContract({
    required String assetName,
    required String ownerAddress,
    required String toAddress,
    required PlatformInt64 amount,
  }) = TronContractValue_TransferAssetContract;
  const factory TronContractValue.voteWitnessContract({
    required String ownerAddress,
    required List<TronVoteInfo> votes,
    required bool support,
  }) = TronContractValue_VoteWitnessContract;
  const factory TronContractValue.accountCreateContract({
    required String ownerAddress,
    required String accountAddress,
  }) = TronContractValue_AccountCreateContract;
  const factory TronContractValue.accountUpdateContract({
    required String ownerAddress,
    required String accountName,
  }) = TronContractValue_AccountUpdateContract;
  const factory TronContractValue.accountPermissionUpdateContract({
    required String ownerAddress,
  }) = TronContractValue_AccountPermissionUpdateContract;
  const factory TronContractValue.unknown({
    required String typeUrl,
    required String valueJson,
  }) = TronContractValue_Unknown;
}

class TronRawDataInfo {
  final List<TronContractInfo> contract;
  final String refBlockBytes;
  final String refBlockHash;
  final PlatformInt64 expiration;
  final PlatformInt64? feeLimit;
  final PlatformInt64 timestamp;

  const TronRawDataInfo({
    required this.contract,
    required this.refBlockBytes,
    required this.refBlockHash,
    required this.expiration,
    this.feeLimit,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      contract.hashCode ^
      refBlockBytes.hashCode ^
      refBlockHash.hashCode ^
      expiration.hashCode ^
      feeLimit.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TronRawDataInfo &&
          runtimeType == other.runtimeType &&
          contract == other.contract &&
          refBlockBytes == other.refBlockBytes &&
          refBlockHash == other.refBlockHash &&
          expiration == other.expiration &&
          feeLimit == other.feeLimit &&
          timestamp == other.timestamp;
}

class TronVoteInfo {
  final String voteAddress;
  final PlatformInt64 voteCount;

  const TronVoteInfo({
    required this.voteAddress,
    required this.voteCount,
  });

  @override
  int get hashCode => voteAddress.hashCode ^ voteCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TronVoteInfo &&
          runtimeType == other.runtimeType &&
          voteAddress == other.voteAddress &&
          voteCount == other.voteCount;
}
