// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Open (PROCESSING) order for the exchange-page badge/modal.
class WhiteBirdOpenOrder {
  final String orderId;
  final String? number;
  final String fromAsset;
  final String toAsset;

  /// Human decimal amounts as reported by WhiteBird.
  final String fromAmount;
  final String toAmount;
  final String status;

  /// `true` when the input leg is a crypto transfer (sell order).
  final bool isSell;

  /// Deposit address awaiting the user's crypto (sell orders only).
  final String? depositAddress;

  /// `true` once WhiteBird has seen the incoming crypto transaction.
  final bool cryptoReceived;
  final String createdAt;
  final String? expiresAt;

  /// WhiteBird client uuid — persisted by Dart for future history lookups.
  final String clientId;

  const WhiteBirdOpenOrder({
    required this.orderId,
    this.number,
    required this.fromAsset,
    required this.toAsset,
    required this.fromAmount,
    required this.toAmount,
    required this.status,
    required this.isSell,
    this.depositAddress,
    required this.cryptoReceived,
    required this.createdAt,
    this.expiresAt,
    required this.clientId,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^
      number.hashCode ^
      fromAsset.hashCode ^
      toAsset.hashCode ^
      fromAmount.hashCode ^
      toAmount.hashCode ^
      status.hashCode ^
      isSell.hashCode ^
      depositAddress.hashCode ^
      cryptoReceived.hashCode ^
      createdAt.hashCode ^
      expiresAt.hashCode ^
      clientId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WhiteBirdOpenOrder &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          number == other.number &&
          fromAsset == other.fromAsset &&
          toAsset == other.toAsset &&
          fromAmount == other.fromAmount &&
          toAmount == other.toAmount &&
          status == other.status &&
          isSell == other.isSell &&
          depositAddress == other.depositAddress &&
          cryptoReceived == other.cryptoReceived &&
          createdAt == other.createdAt &&
          expiresAt == other.expiresAt &&
          clientId == other.clientId;
}

/// Result of `POST /api/sessions` — pre-calculated exchange context.
class WhiteBirdSessionInfo {
  final String sessionId;

  /// Ready-to-open SDK URL (informational; the app embeds via the JS SDK).
  final String sdkUrl;
  final String fromNetAmount;
  final String toNetAmount;
  final String limitMin;
  final String limitMax;

  const WhiteBirdSessionInfo({
    required this.sessionId,
    required this.sdkUrl,
    required this.fromNetAmount,
    required this.toNetAmount,
    required this.limitMin,
    required this.limitMax,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      sdkUrl.hashCode ^
      fromNetAmount.hashCode ^
      toNetAmount.hashCode ^
      limitMin.hashCode ^
      limitMax.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WhiteBirdSessionInfo &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          sdkUrl == other.sdkUrl &&
          fromNetAmount == other.fromNetAmount &&
          toNetAmount == other.toNetAmount &&
          limitMin == other.limitMin &&
          limitMax == other.limitMax;
}
