// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/transactions/access_list.dart';
import '../models/transactions/base_token.dart';
import '../models/transactions/btc.dart';
import '../models/transactions/evm.dart';
import '../models/transactions/request.dart';
import '../models/transactions/scilla.dart';
import '../models/transactions/transaction_metadata.dart';
import '../models/transactions/tron.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_btc_address_lookup`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Parse a dApp PSBT (base64) into Bearby's typed request so the standard
/// confirm-modal → `sign_send_transactions` pipeline can sign/broadcast it.
///
/// Resolves each input's `(addr_type, derivation_path)` by matching the input
/// address against the wallet's BTC address chains; errors if any `signInputs`
/// entry is not a wallet address or requests a non-default sighash.
Future<TransactionRequestInfo> btcPsbtToRequest(
        {required BigInt walletIndex,
        required BigInt accountIndex,
        required String psbtBase64,
        required List<WcSignInputInfo> signInputs,
        required bool broadcast,
        String? title,
        String? icon}) =>
    RustLib.instance.api.crateApiBtcBtcPsbtToRequest(
        walletIndex: walletIndex,
        accountIndex: accountIndex,
        psbtBase64: psbtBase64,
        signInputs: signInputs,
        broadcast: broadcast,
        title: title,
        icon: icon);

/// Signed tx → finalized PSBT (base64). Rebuilds the PSBT from the unsigned
/// skeleton and moves each input's script_sig/witness into
/// `final_script_sig` / `final_script_witness`.
String btcFinalizedPsbtFromSigned(
        {required TransactionBitcoin tx,
        required List<TxOutInfo> witnessUtxos}) =>
    RustLib.instance.api.crateApiBtcBtcFinalizedPsbtFromSigned(
        tx: tx, witnessUtxos: witnessUtxos);

/// BIP-137 ecdsa `signMessage` for an address belonging to the given account.
Future<BtcSignedMessageInfo> btcSignMessageBip137(
        {required BigInt walletIndex,
        required BigInt accountIndex,
        String? password,
        String? passphrase,
        required String address,
        required String message}) =>
    RustLib.instance.api.crateApiBtcBtcSignMessageBip137(
        walletIndex: walletIndex,
        accountIndex: accountIndex,
        password: password,
        passphrase: passphrase,
        address: address,
        message: message);

/// BIP-137 signMessage result for bip122.
class BtcSignedMessageInfo {
  final String address;
  final String signatureBase64;
  final String messageHashHex;

  const BtcSignedMessageInfo({
    required this.address,
    required this.signatureBase64,
    required this.messageHashHex,
  });

  @override
  int get hashCode =>
      address.hashCode ^ signatureBase64.hashCode ^ messageHashHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BtcSignedMessageInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          signatureBase64 == other.signatureBase64 &&
          messageHashHex == other.messageHashHex;
}

/// One entry from WalletConnect `signPsbt.signInputs[]`.
class WcSignInputInfo {
  final String address;
  final int index;
  final Uint32List? sighashTypes;

  const WcSignInputInfo({
    required this.address,
    required this.index,
    this.sighashTypes,
  });

  @override
  int get hashCode => address.hashCode ^ index.hashCode ^ sighashTypes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WcSignInputInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          index == other.index &&
          sighashTypes == other.sighashTypes;
}
