// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/exchange.dart';
import '../models/ftoken.dart';
import '../models/provider.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<ExchangeProviderId> bootstrapExchangeProviders(
        {required List<NetworkConfigInfo> configs}) =>
    RustLib.instance.api
        .crateApiExchangeBootstrapExchangeProviders(configs: configs);

Future<List<ExchangeChainGroup>> fetchExchangeAssets(
        {required ExchangeProviderId provider,
        required List<NetworkConfigInfo> configs}) =>
    RustLib.instance.api.crateApiExchangeFetchExchangeAssets(
        provider: provider, configs: configs);

Future<ExchangeQuoteResult> fetchExchangeQuote(
        {required ExchangeProviderId provider,
        required String fromAsset,
        required String toAsset,
        required String amount,
        required String destination}) =>
    RustLib.instance.api.crateApiExchangeFetchExchangeQuote(
        provider: provider,
        fromAsset: fromAsset,
        toAsset: toAsset,
        amount: amount,
        destination: destination);
