// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/exchange.dart';
import '../models/exchange/pancakeswap.dart';
import '../models/exchange/plunderswap.dart';
import '../models/exchange/relay.dart';
import '../models/exchange/uniswap.dart';
import '../models/ftoken.dart';
import '../models/transactions/base_token.dart';
import '../models/transactions/btc.dart';
import '../models/transactions/history.dart';
import '../models/transactions/transaction_metadata.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<String> executeExchangeSwap(
        {required SwapAuth auth,
        required SwapParams params,
        required ExchangeTxDisplay display}) =>
    RustLib.instance.api.crateApiExchangeExecuteExchangeSwap(
        auth: auth, params: params, display: display);
