// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/walletconnect/ffi.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_wc`

/// Initialize the WalletConnect engine (idempotent if already running).
///
/// `platform`: `"android"` | `"ios"` | `"macos"` | `"linux"` | `"windows"`.
/// `package_name`: Android package / iOS bundle id.
Future<void> wcInit(
        {required String projectId,
        required String appName,
        required String appDescription,
        required String appUrl,
        required String appIcon,
        required String packageName,
        required String platform}) =>
    RustLib.instance.api.crateApiWalletconnectWcInit(
        projectId: projectId,
        appName: appName,
        appDescription: appDescription,
        appUrl: appUrl,
        appIcon: appIcon,
        packageName: packageName,
        platform: platform);

/// Stream engine events into Flutter. Call once after [`wc_init`].
Stream<WcEventInfo> wcEvents() =>
    RustLib.instance.api.crateApiWalletconnectWcEvents();

/// Pair with a dApp via WalletConnect URI (`wc:…@2?…`).
Future<void> wcPair({required String uri}) =>
    RustLib.instance.api.crateApiWalletconnectWcPair(uri: uri);

/// Approve a pending session proposal with CAIP-10 namespaces built by Flutter.
Future<String> wcApproveSession(
        {required BigInt proposalId,
        required List<WcNamespaceApproval> namespaces}) =>
    RustLib.instance.api.crateApiWalletconnectWcApproveSession(
        proposalId: proposalId, namespaces: namespaces);

/// Reject a pending session proposal (error code 5000).
Future<void> wcRejectSession({required BigInt proposalId}) =>
    RustLib.instance.api
        .crateApiWalletconnectWcRejectSession(proposalId: proposalId);

/// Respond to a `wc_sessionRequest` with a JSON result (opaque to the SDK).
Future<void> wcRespondOk(
        {required String topic,
        required BigInt id,
        required String resultJson}) =>
    RustLib.instance.api.crateApiWalletconnectWcRespondOk(
        topic: topic, id: id, resultJson: resultJson);

/// Respond to a `wc_sessionRequest` with a JSON-RPC error.
Future<void> wcRespondErr(
        {required String topic,
        required BigInt id,
        required PlatformInt64 code,
        required String message}) =>
    RustLib.instance.api.crateApiWalletconnectWcRespondErr(
        topic: topic, id: id, code: code, message: message);

/// Disconnect an active session (publish delete + drop local state).
Future<void> wcDisconnect({required String topic}) =>
    RustLib.instance.api.crateApiWalletconnectWcDisconnect(topic: topic);

/// List active sessions.
Future<List<WcSessionInfo>> wcSessions() =>
    RustLib.instance.api.crateApiWalletconnectWcSessions();

/// Shut down the relay and clear the engine singleton.
Future<void> wcShutdown() =>
    RustLib.instance.api.crateApiWalletconnectWcShutdown();
