// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FFI-safe PancakeSwap marker. Only the source chain id is needed — deployment addresses
/// are resolved internally from a const table via [`PancakeMeta::resolve`].
class PancakeMeta {
  final BigInt chainId;

  const PancakeMeta({
    required this.chainId,
  });

  @override
  int get hashCode => chainId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PancakeMeta &&
          runtimeType == other.runtimeType &&
          chainId == other.chainId;
}
