// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../exchange.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PlunderCfg {
  final int defaultSlippageBps;
  final bool supportsPriceProtection;

  const PlunderCfg({
    required this.defaultSlippageBps,
    required this.supportsPriceProtection,
  });

  @override
  int get hashCode =>
      defaultSlippageBps.hashCode ^ supportsPriceProtection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlunderCfg &&
          runtimeType == other.runtimeType &&
          defaultSlippageBps == other.defaultSlippageBps &&
          supportsPriceProtection == other.supportsPriceProtection;
}

class PlunderMeta {
  final ProviderCommon common;
  final PlunderCfg cfg;
  final ProviderQuote? quote;

  const PlunderMeta({
    required this.common,
    required this.cfg,
    this.quote,
  });

  @override
  int get hashCode => common.hashCode ^ cfg.hashCode ^ quote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlunderMeta &&
          runtimeType == other.runtimeType &&
          common == other.common &&
          cfg == other.cfg &&
          quote == other.quote;
}
