// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RelayMeta {
  /// Bearby provider hash for the asset's chain.
  final BigInt chainHash;

  /// Relay chain id. EVM chains use their normal EIP-155 id; Solana and Bitcoin use Relay's
  /// synthetic ids.
  final BigInt chainId;

  /// Bearby/BIP slip44 for address-family checks and future VM-specific finalizers.
  final int slip44;

  /// Selected wallet account address on this asset's chain. Relay uses the source asset's address
  /// as `user` and the destination asset's address as `recipient`.
  final String accountAddr;

  const RelayMeta({
    required this.chainHash,
    required this.chainId,
    required this.slip44,
    required this.accountAddr,
  });

  @override
  int get hashCode =>
      chainHash.hashCode ^
      chainId.hashCode ^
      slip44.hashCode ^
      accountAddr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayMeta &&
          runtimeType == other.runtimeType &&
          chainHash == other.chainHash &&
          chainId == other.chainId &&
          slip44 == other.slip44 &&
          accountAddr == other.accountAddr;
}
