// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FFI-safe THORChain provider metadata, populated per token in `bootstrap_exchange_providers`
/// (mirrors [`super::UniswapMeta`]). Carries the asset's resolved THORChain identity so the
/// quote/swap engine never re-derives it: the `chain` id (e.g. `ETH`, `BSC`, `BTC`), the full
/// `asset` id (e.g. `ETH.USDC-0x…`, `BTC.BTC`), and the EVM `chain_id` (`0` for non-EVM source).
class ThorchainMeta {
  final String chain;
  final String asset;
  final BigInt chainId;

  const ThorchainMeta({
    required this.chain,
    required this.asset,
    required this.chainId,
  });

  @override
  int get hashCode => chain.hashCode ^ asset.hashCode ^ chainId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThorchainMeta &&
          runtimeType == other.runtimeType &&
          chain == other.chain &&
          asset == other.asset &&
          chainId == other.chainId;
}
