// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FFI-safe Uniswap marker. Only the source chain id is needed — the Trading API resolves
/// routers, pools and routing itself. Carried inside [`ExchangeProvider::Uniswap`].
class UniswapMeta {
  final BigInt chainId;

  const UniswapMeta({
    required this.chainId,
  });

  @override
  int get hashCode => chainId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UniswapMeta &&
          runtimeType == other.runtimeType &&
          chainId == other.chainId;
}
