// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../exchange.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Provider meta crossing FRB as `ExchangeProvider::WhiteBird`.
class WhiteBirdMeta {
  final ProviderCommon common;
  final ProviderQuote? quote;

  /// WhiteBird asset id for the token this meta is attached to
  /// (`"TRX"`, `"USDT_TRC"`, `"BYN"`, …).
  final String assetCode;

  /// `true` when attached to a synthetic fiat token.
  final bool isFiat;

  /// testnet → wbdev.bearby.ru, mainnet → wb.bearby.ru.
  final bool isTestnet;

  const WhiteBirdMeta({
    required this.common,
    this.quote,
    required this.assetCode,
    required this.isFiat,
    required this.isTestnet,
  });

  @override
  int get hashCode =>
      common.hashCode ^
      quote.hashCode ^
      assetCode.hashCode ^
      isFiat.hashCode ^
      isTestnet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WhiteBirdMeta &&
          runtimeType == other.runtimeType &&
          common == other.common &&
          quote == other.quote &&
          assetCode == other.assetCode &&
          isFiat == other.isFiat &&
          isTestnet == other.isTestnet;
}
