// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ffi.freezed.dart';

@freezed
sealed class WcEventInfo with _$WcEventInfo {
  const WcEventInfo._();

  const factory WcEventInfo.proposal(
    WcProposalInfo field0,
  ) = WcEventInfo_Proposal;
  const factory WcEventInfo.request(
    WcRequestInfo field0,
  ) = WcEventInfo_Request;
  const factory WcEventInfo.sessionSettled({
    required String topic,
  }) = WcEventInfo_SessionSettled;
  const factory WcEventInfo.sessionDeleted({
    required String topic,
    required String message,
  }) = WcEventInfo_SessionDeleted;
  const factory WcEventInfo.sessionEvent({
    required String topic,
    required String chainId,
    required String name,
    required String data,
  }) = WcEventInfo_SessionEvent;
  const factory WcEventInfo.relayConnected() = WcEventInfo_RelayConnected;
  const factory WcEventInfo.relayDisconnected() = WcEventInfo_RelayDisconnected;
  const factory WcEventInfo.error({
    required String message,
  }) = WcEventInfo_Error;
}

/// Built by Flutter when approving a session.
class WcNamespaceApproval {
  final String key;
  final List<String> accounts;
  final List<String> methods;
  final List<String> events;

  const WcNamespaceApproval({
    required this.key,
    required this.accounts,
    required this.methods,
    required this.events,
  });

  @override
  int get hashCode =>
      key.hashCode ^ accounts.hashCode ^ methods.hashCode ^ events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WcNamespaceApproval &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          accounts == other.accounts &&
          methods == other.methods &&
          events == other.events;
}

class WcNamespaceInfo {
  final String key;
  final List<String> chains;
  final List<String> methods;
  final List<String> events;

  const WcNamespaceInfo({
    required this.key,
    required this.chains,
    required this.methods,
    required this.events,
  });

  @override
  int get hashCode =>
      key.hashCode ^ chains.hashCode ^ methods.hashCode ^ events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WcNamespaceInfo &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          chains == other.chains &&
          methods == other.methods &&
          events == other.events;
}

class WcProposalInfo {
  final BigInt id;
  final String pairingTopic;
  final String peerName;
  final String peerDescription;
  final String peerUrl;
  final String? peerIcon;
  final List<WcNamespaceInfo> required_;
  final List<WcNamespaceInfo> optional;

  const WcProposalInfo({
    required this.id,
    required this.pairingTopic,
    required this.peerName,
    required this.peerDescription,
    required this.peerUrl,
    this.peerIcon,
    required this.required_,
    required this.optional,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pairingTopic.hashCode ^
      peerName.hashCode ^
      peerDescription.hashCode ^
      peerUrl.hashCode ^
      peerIcon.hashCode ^
      required_.hashCode ^
      optional.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WcProposalInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pairingTopic == other.pairingTopic &&
          peerName == other.peerName &&
          peerDescription == other.peerDescription &&
          peerUrl == other.peerUrl &&
          peerIcon == other.peerIcon &&
          required_ == other.required_ &&
          optional == other.optional;
}

class WcRequestInfo {
  final String topic;
  final BigInt id;
  final String chainId;
  final String method;
  final String paramsJson;
  final String peerName;
  final String? peerIcon;

  const WcRequestInfo({
    required this.topic,
    required this.id,
    required this.chainId,
    required this.method,
    required this.paramsJson,
    required this.peerName,
    this.peerIcon,
  });

  @override
  int get hashCode =>
      topic.hashCode ^
      id.hashCode ^
      chainId.hashCode ^
      method.hashCode ^
      paramsJson.hashCode ^
      peerName.hashCode ^
      peerIcon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WcRequestInfo &&
          runtimeType == other.runtimeType &&
          topic == other.topic &&
          id == other.id &&
          chainId == other.chainId &&
          method == other.method &&
          paramsJson == other.paramsJson &&
          peerName == other.peerName &&
          peerIcon == other.peerIcon;
}

class WcSessionInfo {
  final String topic;
  final String peerName;
  final String peerDescription;
  final String peerUrl;
  final String? peerIcon;
  final List<String> accounts;
  final List<String> methods;
  final List<String> events;
  final BigInt expiry;

  const WcSessionInfo({
    required this.topic,
    required this.peerName,
    required this.peerDescription,
    required this.peerUrl,
    this.peerIcon,
    required this.accounts,
    required this.methods,
    required this.events,
    required this.expiry,
  });

  @override
  int get hashCode =>
      topic.hashCode ^
      peerName.hashCode ^
      peerDescription.hashCode ^
      peerUrl.hashCode ^
      peerIcon.hashCode ^
      accounts.hashCode ^
      methods.hashCode ^
      events.hashCode ^
      expiry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WcSessionInfo &&
          runtimeType == other.runtimeType &&
          topic == other.topic &&
          peerName == other.peerName &&
          peerDescription == other.peerDescription &&
          peerUrl == other.peerUrl &&
          peerIcon == other.peerIcon &&
          accounts == other.accounts &&
          methods == other.methods &&
          events == other.events &&
          expiry == other.expiry;
}
